# Generated by Django 4.1.5 on 2023-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("logo_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
