# Generated by Django 4.1.5 on 2023-01-09 18:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("content", models.TextField()),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo_text",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="brand_color",
            field=colorfield.fields.ColorField(
                default="#618A5F", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="primary_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                default="#D9D9D9", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
