# Generated by Django 4.1.5 on 2023-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_page_remove_sitesettings_logo_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
