# Generated by Django 4.1.5 on 2023-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_page_icon_sitesettings_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
