# Generated by Django 4.1.5 on 2023-01-09 18:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_page_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
