# Generated by Django 4.1.5 on 2023-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
