# Generated by Django 4.1.5 on 2023-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_sitesettings_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
