# Generated by Django 4.1.5 on 2023-01-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20230114_1036"),
    ]

    operations = []
