# Generated by Django 4.1.5 on 2023-01-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_sitesettings_favicon"),
    ]

    operations = []
