# Generated by Django 4.1.5 on 2023-01-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_news_image_remove_page_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_image",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_image",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_image",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logo",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_image",
                to="api.image",
            ),
        ),
    ]
