# Generated by Django 4.1.5 on 2023-01-16 11:42

from django.db import migrations
from pathlib import Path
from PIL import Image as PILImage
import os


def convert_image_to_webp(apps, schema_editor):
    Image = apps.get_model("api", "Image")
    for image in Image.objects.all():
        if image.image.name.endswith(".ico"):
            return
        file_path = Path(image.image.path).resolve()
        image = PILImage.open(file_path)
        webp_file_path = file_path.with_suffix(".webp")
        image.save(webp_file_path, "WebP")
        image.image = str(webp_file_path)
        os.remove(file_path)
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_news_image_page_image_sitesettings_background_image_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_image_to_webp),
    ]
