# Generated by Django 4.1.5 on 2023-01-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20230116_1242"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo",
        ),
    ]
