# Generated by Django 4.1.5 on 2023-01-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_sitesettings_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="icon",
        ),
    ]
