# Generated by Django 4.1.5 on 2023-01-09 18:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
