# Generated by Django 4.1.5 on 2023-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_page_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
