# Generated by Django 4.1.5 on 2023-01-11 16:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_sitesettings_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
