# Generated by Django 4.1.5 on 2023-01-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(blank=True, to="api.category"),
        ),
    ]
