# Generated by Django 4.1.5 on 2023-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_contactdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdetails",
            name="name",
            field=models.CharField(default="Contact", max_length=255),
        ),
    ]
