# Generated by Django 4.1.5 on 2023-01-13 17:20

from django.db import migrations

from django.utils.text import slugify


def add_slug(apps, schema_editor):
    News = apps.get_model("api", "News")
    for news in News.objects.all():
        news.slug = slugify(news.title + "-" + str(news.date_published) + "-" + str(news.id))
        news.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_news_slug"),
    ]

    operations = [
        migrations.RunPython(add_slug),
    ]
