# Generated by Django 4.1.5 on 2023-01-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20230113_1820"),
    ]

    operations = []
