# Generated by Django 4.1.5 on 2023-01-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_news_image_alter_page_image_and_more"),
    ]

    operations = []
