# Generated by Django 4.1.5 on 2023-01-16 11:08

from django.db import migrations, models


def migrateOldImagesToNewModel(apps, schema_editor):
    SiteSettings = apps.get_model("api", "SiteSettings")
    Page = apps.get_model("api", "Page")
    News = apps.get_model("api", "News")
    Image = apps.get_model("api", "Image")

    for site_settings in SiteSettings.objects.all():
        if site_settings.favicon:
            Image.objects.create(
                name="favicon",
                image=site_settings.favicon,
                alt="Favicon",
            )
        if site_settings.logo:
            Image.objects.create(
                name="logo",
                image=site_settings.logo,
                alt="Logo",
            )
        if site_settings.background_image:
            Image.objects.create(
                name="background_image",
                image=site_settings.background_image,
                alt="Background Image",
            )
        if site_settings.main_image:
            Image.objects.create(
                name="main_image",
                image=site_settings.main_image,
                alt="Main Image",
            )

    for page in Page.objects.all():
        if page.image:
            Image.objects.create(
                name="image",
                image=page.image,
                alt="Image",
            )

    for news in News.objects.all():
        if news.image:
            Image.objects.create(
                name="image",
                image=news.image,
                alt="Image",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_news_image_alter_page_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("alt", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RunPython(migrateOldImagesToNewModel),
    ]
