# Generated by Django 4.1.5 on 2023-01-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.RemoveField(
            model_name="page",
            name="image",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="main_image",
        ),
    ]
