# Generated by Django 4.1.5 on 2023-01-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_remove_page_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_icon",
                to="api.image",
            ),
        ),
    ]
