# Generated by Django 4.1.5 on 2023-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_icon_alter_page_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='show_contact_form',
            field=models.BooleanField(default=True),
        ),
    ]
