# Generated by Django 4.1.5 on 2023-01-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_contactdetails_show_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
