# Generated by Django 4.1.5 on 2023-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_contactdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='main_images',
            field=models.ManyToManyField(blank=True, related_name='main_images', to='api.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
