# Generated by Django 4.1.5 on 2023-01-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_sitesettings_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='main_images',
            new_name='hero_images',
        ),
    ]
